/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CostBasisRouteImport } from './routes/cost-basis'
import { Route as IndexRouteImport } from './routes/index'

const CostBasisRoute = CostBasisRouteImport.update({
  id: '/cost-basis',
  path: '/cost-basis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cost-basis': typeof CostBasisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cost-basis': typeof CostBasisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cost-basis': typeof CostBasisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cost-basis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cost-basis'
  id: '__root__' | '/' | '/cost-basis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CostBasisRoute: typeof CostBasisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cost-basis': {
      id: '/cost-basis'
      path: '/cost-basis'
      fullPath: '/cost-basis'
      preLoaderRoute: typeof CostBasisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CostBasisRoute: CostBasisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
